# Generated by Django 4.2 on 2025-09-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('mat_emp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('code_equip', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('code_ligne', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Navette',
            fields=[
                ('nda', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_service', models.DateField()),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employe')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ligne')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipement')),
            ],
        ),
    ]
