# Generated by Django 4.2 on 2025-09-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
