# Generated by Django 4.2 on 2025-09-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ligne_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='destination',
        ),
    ]
