# Generated by Django 5.0.2 on 2026-02-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('mat_emp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_emp', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'employe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('cod_equ', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dat_mod_equ', models.DateField(blank=True, null=True)),
                ('des_equ', models.CharField(blank=True, max_length=255, null=True)),
                ('dat_aqu_equ', models.DateField(blank=True, null=True)),
                ('mnt_aqu_equ', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cou_arr_equ', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('dat_fin_gar_equ', models.DateField(blank=True, null=True)),
                ('uni_cou_arr_equ', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('dat_ins_equ', models.DateField(blank=True, null=True)),
                ('ref_fab_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('mrq_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('mai_ext_equ', models.CharField(blank=True, max_length=1, null=True)),
                ('int_sur_aut_equ', models.CharField(blank=True, max_length=1, null=True)),
                ('ann_fab_equ', models.IntegerField(blank=True, default=0, null=True)),
                ('cod_inv_equ', models.CharField(blank=True, max_length=50, null=True)),
                ('mod_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('obs_equ', models.CharField(blank=True, max_length=255, null=True)),
                ('anc_cod_equ', models.CharField(blank=True, max_length=50, null=True)),
                ('per_amo_equ', models.IntegerField(blank=True, default=0, null=True)),
                ('eta_equ', models.CharField(blank=True, max_length=1, null=True)),
                ('fab_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('num_ser_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('imm_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('fra_acc_equ', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cod_fon', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_cri', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_loc', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_fam_equ', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_equ_per', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_fou', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_sta', models.SmallIntegerField()),
                ('dat_sta_equ', models.DateField(blank=True, null=True)),
                ('dat_cre_equ', models.DateField(blank=True, null=True)),
                ('use_cre_equ', models.CharField(blank=True, max_length=50, null=True)),
                ('use_mod_equ', models.CharField(blank=True, max_length=50, null=True)),
                ('mnt_amo_equi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('eta_phy_equ', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'equipement',
            },
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('origine', models.CharField(max_length=100)),
                ('dest', models.CharField(max_length=100)),
                ('agence', models.CharField(blank=True, max_length=50, null=True)),
                ('klm', models.IntegerField(blank=True, null=True)),
                ('actif', models.SmallIntegerField(default=1)),
                ('sortie', models.IntegerField(blank=True, null=True)),
                ('ord', models.IntegerField(blank=True, null=True)),
                ('nch', models.IntegerField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('sv', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ligne',
            },
        ),
        migrations.CreateModel(
            name='Locatile',
            fields=[
                ('cod_loc', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lib_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('adr_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_loc_loc', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_vil', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locatile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Navette',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asens', models.CharField(max_length=5)),
                ('atypsrv', models.CharField(max_length=5)),
                ('nda', models.IntegerField()),
                ('adatserv', models.DateField(blank=True, null=True)),
                ('ags', models.CharField(blank=True, max_length=50, null=True)),
                ('rem', models.CharField(blank=True, max_length=50, null=True)),
                ('ndr', models.IntegerField(blank=True, null=True)),
                ('achauffeur', models.ForeignKey(blank=True, db_column='achauffeur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navettes_principales', to='blog.employe')),
                ('aveh', models.ForeignKey(blank=True, db_column='aveh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navettes_aller', to='blog.equipement')),
                ('ligne', models.ForeignKey(db_column='ligne', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.ligne')),
                ('rchauffeur', models.ForeignKey(blank=True, db_column='rchauffeur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navettes_retour', to='blog.employe')),
                ('rveh', models.ForeignKey(blank=True, db_column='rveh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navettes_retour', to='blog.equipement')),
            ],
            options={
                'db_table': 'navette',
                'permissions': [('can_add_navette_form', 'Can access navette manage page')],
                'managed': True,
                'unique_together': {('ligne', 'asens', 'atypsrv', 'adatserv')},
            },
        ),
    ]
