# Generated by Django 4.2 on 2025-09-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navette',
            fields=[
                ('id_navette', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('depart', models.CharField(max_length=50)),
                ('arrivee', models.CharField(max_length=50)),
                ('date_depart', models.DateTimeField()),
            ],
            options={
                'db_table': 'NAVETTE',
                'managed': False,
            },
        ),
    ]
