# Generated by Django 5.0.2 on 2026-03-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navette',
            name='asens',
            field=models.CharField(blank=True, default='A', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='navette',
            name='atypsrv',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='navette',
            name='nda',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
