# Generated by Django 4.2 on 2025-09-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navette',
            options={},
        ),
    ]
