# Generated by Django 5.0.2 on 2026-02-12 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ligne',
            options={},
        ),
        migrations.AlterField(
            model_name='navette',
            name='adatserv',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navette',
            name='aveh',
            field=models.ForeignKey(blank=True, db_column='aveh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navettes_aller', to='blog.equipement'),
        ),
        migrations.AlterField(
            model_name='navette',
            name='rveh',
            field=models.ForeignKey(blank=True, db_column='rveh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navettes_retour', to='blog.equipement'),
        ),
    ]
