# Generated by Django 4.2 on 2025-10-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_navette_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('mat_emp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_emp', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'employe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('origine', models.CharField(max_length=100)),
                ('dest', models.CharField(max_length=100)),
                ('agence', models.CharField(blank=True, max_length=50, null=True)),
                ('klm', models.IntegerField(blank=True, null=True)),
                ('actif', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'ligne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('cod_equ', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dat_mod_equ', models.DateField(blank=True, null=True)),
                ('des_equ', models.CharField(blank=True, max_length=255, null=True)),
                ('dat_aqu_equ', models.DateField(blank=True, null=True)),
                ('mnt_aqu_equ', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cou_arr_equ', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('dat_fin_gar_equ', models.DateField(blank=True, null=True)),
                ('uni_cou_arr_equ', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('dat_ins_equ', models.DateField(blank=True, null=True)),
                ('ref_fab_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('mrq_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('mai_ext_equ', models.CharField(blank=True, max_length=1, null=True)),
                ('int_sur_aut_equ', models.CharField(blank=True, max_length=1, null=True)),
                ('ann_fab_equ', models.IntegerField(blank=True, default=0, null=True)),
                ('cod_inv_equ', models.CharField(blank=True, max_length=50, null=True)),
                ('mod_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('obs_equ', models.CharField(blank=True, max_length=255, null=True)),
                ('anc_cod_equ', models.CharField(blank=True, max_length=50, null=True)),
                ('per_amo_equ', models.IntegerField(blank=True, default=0, null=True)),
                ('eta_equ', models.CharField(blank=True, max_length=1, null=True)),
                ('fab_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('num_ser_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('imm_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('fra_acc_equ', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cod_fon', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_cri', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_loc', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_fam_equ', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_equ_per', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_fou', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_sta', models.SmallIntegerField()),
                ('dat_sta_equ', models.DateField(blank=True, null=True)),
                ('dat_cre_equ', models.DateField(blank=True, null=True)),
                ('use_cre_equ', models.CharField(blank=True, max_length=50, null=True)),
                ('use_mod_equ', models.CharField(blank=True, max_length=50, null=True)),
                ('mnt_amo_equi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('eta_phy_equ', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'equipement',
            },
        ),
        migrations.CreateModel(
            name='Locatile',
            fields=[
                ('cod_loc', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lib_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('adr_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_loc_loc', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_vil', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locatile',
            },
        ),
        migrations.AlterModelOptions(
            name='navette',
            options={'managed': False},
        ),
    ]
