# Generated by Django 5.0.2 on 2026-02-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_ligne_options_alter_navette_adatserv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navette',
            options={'managed': True, 'permissions': [('can_add_navette_form', 'Can access navette manage page')]},
        ),
    ]
