# Generated by Django 4.2 on 2025-10-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_employe_ligne_equipement_locatile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locatile',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='navette',
            table='navette',
        ),
    ]
