# Generated by Django 5.0.2 on 2025-12-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_locatile_options_alter_navette_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ligne',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='locatile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='navette',
            options={'managed': True},
        ),
    ]
