# Generated by Django 5.0.2 on 2025-12-04 10:51

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_employe_options_alter_ligne_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navette',
            name='adatserv',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),

        migrations.AlterUniqueTogether(
            name='navette',
            unique_together={('ligne', 'asens', 'atypsrv', 'adatserv')},
        ),
        migrations.AddField(
            model_name='ligne',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ligne',
            name='nch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligne',
            name='ord',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligne',
            name='sortie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligne',
            name='sv',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='navette',
            name='achauffeur',
            field=models.ForeignKey(blank=True, db_column='achauffeur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navettes_principales', to='blog.employe'),
        ),
        migrations.AddField(
            model_name='navette',
            name='ags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navette',
            name='asens',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navette',
            name='atypsrv',
            field=models.CharField(default='rbs', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navette',
            name='aveh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navette',
            name='id',
            field=models.AutoField(default='rbs', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navette',
            name='ligne',
            field=models.ForeignKey(db_column='ligne', default='rbs', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.ligne'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navette',
            name='nda',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navette',
            name='ndr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='navette',
            name='rchauffeur',
            field=models.ForeignKey(blank=True, db_column='rchauffeur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navettes_retour', to='blog.employe'),
        ),
        migrations.AddField(
            model_name='navette',
            name='rem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navette',
            name='rveh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='navette',
            name='arrivee',
        ),
        migrations.RemoveField(
            model_name='navette',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='navette',
            name='id_navette',
        ),
        migrations.RemoveField(
            model_name='navette',
            name='nom',
        ),
    ]
